plugins {
    id 'java'
}

group = 'org.springframework'
version = '6.1.21-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(":spring-context")
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}