plugins {
    id 'java'
}

group = 'org.springframework'
version = '6.1.21-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(":spring-context")
    implementation project(":spring-test")
    implementation project(":spring-tx")
    implementation("jakarta.annotation:jakarta.annotation-api:2.1.1")
    implementation("jakarta.inject:jakarta.inject-api:2.0.1")
    implementation("org.aspectj:aspectjweaver:1.9.24")
    implementation("org.projectlombok:lombok:1.18.38")
    /* @ImportResource("*.groovy") */
    implementation("org.codehaus.groovy:groovy-all:3.0.21")
    /* slf4j */
    implementation("org.slf4j:slf4j-api:2.0.17")
    implementation("ch.qos.logback:logback-classic:1.5.18")
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}