/*
 * Copyright 2003 The Apache Software Foundation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.springframework.cglib.core;

/**
 * Customize the generated class name for {@link AbstractClassGenerator}-based utilities.
 */
// 自定义基于 {@link AbstractClassGenerator} 的实用程序生成的类名。
public interface NamingPolicy {
    /**
     * Choose a name for a generated class.
     * @param prefix a dotted-name chosen by the generating class (possibly to put the generated class in a particular package)
     * @param source the fully-qualified class name of the generating class (for example "org.springframework.cglib.Enhancer")
     * @param key A key object representing the state of the parameters; for caching to work properly, equal keys should result
     * in the same generated class name. The default policy incorporates <code>key.hashCode()</code> into the class name.
     * @param names a predicate that returns true if the given classname has already been used in the same ClassLoader.
     * @return the fully-qualified class name
     */
	// 为生成的类选择一个名称。
	// @param prefix 生成类选择的带点的名称前缀（可能用于将生成的类放在特定的包中）。
	// @param source 生成类的完全限定类名（例如 "org.springframework.cglib.Enhancer")。
	// @param key 表示参数状态的键对象；为了使缓存正常工作，相同的键应该生成相同的类名。默认策略是将 `<code>key.hashCode()</code>` 合并到类名中。
	// @param names 一个谓词，如果给定的类名已在同一个 ClassLoader 中使用，则返回 true。
	// @return 完全限定类名。
    String getClassName(String prefix, String source, Object key, Predicate names);

    /**
     * The <code>NamingPolicy</code> in use does not currently, but may
     * in the future, affect the caching of classes generated by {@link
     * AbstractClassGenerator}, so this is a reminder that you should
     * correctly implement <code>equals</code> and <code>hashCode</code>
     * to avoid generating too many classes.
     */
	// 目前使用的 <code>NamingPolicy</code> 不会影响 {@link AbstractClassGenerator} 生成的类的缓存，
	// 但将来可能会影响，因此提醒您应正确实现 <code>equals</code> 和 <code>hashCode</code>，以避免生成过多的类。
    @Override
    boolean equals(Object o);
}
