plugins {
    id 'java'
}

group = 'org.springframework'
version = '6.1.21-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':spring-webmvc')
    implementation('org.apache.tomcat.embed:tomcat-embed-core:11.0.7')
    implementation('org.apache.tomcat.embed:tomcat-embed-jasper:11.0.7')
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}